# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CEVSI <- function(samples, z, futureSampleSizes, nSim, ignore_prior = FALSE, debug = FALSE) {
    .Call(`_evsiexval_CEVSI`, samples, z, futureSampleSizes, nSim, ignore_prior, debug)
}

