# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CEVSI <- function(samples, z, futureSampleSizes, nSim, debug = FALSE) {
    .Call('_EVSIExval_CEVSI', PACKAGE = 'EVSIExval', samples, z, futureSampleSizes, nSim, debug)
}

ldExp <- function(x) {
    .Call('_EVSIExval_ldExp', PACKAGE = 'EVSIExval', x)
}

doubleSize <- function() {
    .Call('_EVSIExval_doubleSize', PACKAGE = 'EVSIExval')
}

